USE [master]
GO

/****** Object:  Database [NYC_Taxi]    Script Date: 8/30/2021 9:52:17 PM ******/
CREATE DATABASE [NYC_Taxi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NYC_Taxi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\NYC_Taxi.mdf' , SIZE = 5120000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NYC_Taxi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\NYC_Taxi_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NYC_Taxi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NYC_Taxi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NYC_Taxi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NYC_Taxi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NYC_Taxi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NYC_Taxi] SET ARITHABORT OFF 
GO

ALTER DATABASE [NYC_Taxi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NYC_Taxi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NYC_Taxi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NYC_Taxi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NYC_Taxi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NYC_Taxi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NYC_Taxi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NYC_Taxi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NYC_Taxi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NYC_Taxi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NYC_Taxi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NYC_Taxi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NYC_Taxi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NYC_Taxi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NYC_Taxi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NYC_Taxi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NYC_Taxi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NYC_Taxi] SET RECOVERY FULL 
GO

ALTER DATABASE [NYC_Taxi] SET  MULTI_USER 
GO

ALTER DATABASE [NYC_Taxi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NYC_Taxi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NYC_Taxi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NYC_Taxi] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NYC_Taxi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NYC_Taxi] SET  READ_WRITE 
GO


